import React, { useState, useEffect, useCallback } from 'react';
import { supplierService } from '../../services/supplierService';

// Generate short code from vendor name
const generateShortCode = (name) => {
  if (!name) return '';
  // Remove common suffixes and clean the name
  const cleaned = name
    .replace(/\b(inc|llc|ltd|corp|corporation|company|co|enterprises?|industries?|international|intl)\b\.?/gi, '')
    .trim();

  // Split into words
  const words = cleaned.split(/[\s\-_&]+/).filter(w => w.length > 0);

  if (words.length === 0) return '';

  if (words.length === 1) {
    // Single word - take first 4 characters
    return words[0].substring(0, 4).toUpperCase();
  }

  if (words.length === 2) {
    // Two words - take first 2 chars of each
    return (words[0].substring(0, 2) + words[1].substring(0, 2)).toUpperCase();
  }

  // 3+ words - take first char of first 4 words
  return words.slice(0, 4).map(w => w[0]).join('').toUpperCase();
};

export const SupplierEditModal = ({ supplierId, supplier: initialSupplier, onClose, onSave }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [nameError, setNameError] = useState(null);
  const [allSuppliers, setAllSuppliers] = useState([]);
  const isCreateMode = !supplierId; // No ID = creating new supplier

  const [formData, setFormData] = useState({
    name: '',
    short_code: '',
    contact_name: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    state: '',
    zip: '',
    country: 'USA',
    website: '',
    account_number: '',
    payment_terms: 'Net 30',
    shipping_account: '',
    notes: '',
    is_active: true,
    is_preferred: false
  });

  // Load all suppliers on mount for uniqueness check
  useEffect(() => {
    const loadSuppliers = async () => {
      try {
        const suppliers = await supplierService.getAllSuppliers();
        setAllSuppliers(suppliers);
      } catch (err) {
        console.error('Failed to load suppliers for validation:', err);
      }
    };
    loadSuppliers();
  }, []);

  useEffect(() => {
    if (initialSupplier && !isCreateMode) {
      // Edit mode - populate from existing supplier
      setFormData({
        name: initialSupplier.name || '',
        short_code: initialSupplier.short_code || '',
        contact_name: initialSupplier.contact_name || '',
        email: initialSupplier.email || '',
        phone: initialSupplier.phone || '',
        address: initialSupplier.address || '',
        city: initialSupplier.city || '',
        state: initialSupplier.state || '',
        zip: initialSupplier.zip || '',
        country: initialSupplier.country || 'USA',
        website: initialSupplier.website || '',
        account_number: initialSupplier.account_number || '',
        payment_terms: initialSupplier.payment_terms || 'Net 30',
        shipping_account: initialSupplier.shipping_account || '',
        notes: initialSupplier.notes || '',
        is_active: initialSupplier.is_active !== false,
        is_preferred: initialSupplier.is_preferred || false
      });
    }
  }, [initialSupplier, isCreateMode]);

  // Check if vendor name is unique
  const checkNameUnique = useCallback((name) => {
    if (!name.trim()) {
      setNameError(null);
      return true;
    }
    const normalizedName = name.trim().toLowerCase();
    const isDuplicate = allSuppliers.some(s => {
      // Skip self in edit mode
      if (!isCreateMode && s.id === supplierId) return false;
      return s.name.toLowerCase() === normalizedName;
    });
    if (isDuplicate) {
      setNameError('A supplier with this name already exists');
      return false;
    }
    setNameError(null);
    return true;
  }, [allSuppliers, isCreateMode, supplierId]);

  const handleChange = (field, value) => {
    setFormData(prev => {
      const updated = { ...prev, [field]: value };

      // When name changes, auto-generate short_code and contact_name
      if (field === 'name') {
        // Check uniqueness
        checkNameUnique(value);

        // Auto-generate short code if it's empty or was auto-generated before
        const currentShortCode = prev.short_code;
        const wasAutoGenerated = !currentShortCode || currentShortCode === generateShortCode(prev.name);
        if (wasAutoGenerated) {
          updated.short_code = generateShortCode(value);
        }

        // Auto-populate contact name from vendor name if contact_name is empty
        if (!prev.contact_name) {
          updated.contact_name = value;
        }
      }

      return updated;
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    try {
      // Validate required fields
      if (!formData.name.trim()) {
        throw new Error('Supplier name is required');
      }
      if (!formData.short_code.trim()) {
        throw new Error('Short code is required');
      }

      // Check name uniqueness
      if (!checkNameUnique(formData.name)) {
        throw new Error('A supplier with this name already exists');
      }

      let result;
      if (isCreateMode) {
        // Create new supplier
        result = await supplierService.createSupplier(formData);
      } else {
        // Update existing supplier
        result = await supplierService.updateSupplier(supplierId, formData);
      }

      if (onSave) onSave(result);
      onClose();
    } catch (err) {
      console.error(`Failed to ${isCreateMode ? 'create' : 'update'} supplier:`, err);
      setError(err.message || `Failed to ${isCreateMode ? 'create' : 'update'} supplier`);
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-900 rounded-lg shadow-xl max-w-3xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white">
            {isCreateMode ? 'Add New Supplier' : 'Edit Supplier'}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-6">
          {error && (
            <div className="mb-4 p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded text-sm text-red-800 dark:text-red-200">
              {error}
            </div>
          )}

          {/* Basic Info */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Basic Information</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Supplier Name *
                </label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => handleChange('name', e.target.value)}
                  className={`w-full px-3 py-2 border rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white ${
                    nameError
                      ? 'border-red-500 dark:border-red-500'
                      : 'border-gray-300 dark:border-gray-600'
                  }`}
                  required
                />
                {nameError && (
                  <p className="text-xs text-red-500 mt-1">{nameError}</p>
                )}
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Short Code * <span className="text-xs font-normal text-gray-500">(auto-generated)</span>
                </label>
                <input
                  type="text"
                  value={formData.short_code}
                  onChange={(e) => handleChange('short_code', e.target.value.toUpperCase())}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white uppercase"
                  maxLength={10}
                  required
                />
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  Used in PO numbers - you can edit if needed
                </p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Payment Terms
                </label>
                <select
                  value={formData.payment_terms}
                  onChange={(e) => handleChange('payment_terms', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                >
                  <option value="Net 30">Net 30</option>
                  <option value="Net 45">Net 45</option>
                  <option value="Net 60">Net 60</option>
                  <option value="Due on Receipt">Due on Receipt</option>
                  <option value="COD">COD</option>
                  <option value="Prepaid">Prepaid</option>
                </select>
              </div>
            </div>
          </div>

          {/* Contact Info */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Contact Information</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Contact Name
                </label>
                <input
                  type="text"
                  value={formData.contact_name}
                  onChange={(e) => handleChange('contact_name', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Email
                </label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => handleChange('email', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Phone
                </label>
                <input
                  type="tel"
                  value={formData.phone}
                  onChange={(e) => handleChange('phone', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
            </div>
          </div>

          {/* Address */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Address</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Street Address
                </label>
                <input
                  type="text"
                  value={formData.address}
                  onChange={(e) => handleChange('address', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  City
                </label>
                <input
                  type="text"
                  value={formData.city}
                  onChange={(e) => handleChange('city', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  State
                </label>
                <input
                  type="text"
                  value={formData.state}
                  onChange={(e) => handleChange('state', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                  maxLength={2}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  ZIP Code
                </label>
                <input
                  type="text"
                  value={formData.zip}
                  onChange={(e) => handleChange('zip', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Country
                </label>
                <input
                  type="text"
                  value={formData.country}
                  onChange={(e) => handleChange('country', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
            </div>
          </div>

          {/* Additional Info */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Additional Information</h3>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Website
                </label>
                <input
                  type="url"
                  value={formData.website}
                  onChange={(e) => handleChange('website', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                  placeholder="https://"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Account Number
                </label>
                <input
                  type="text"
                  value={formData.account_number}
                  onChange={(e) => handleChange('account_number', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Shipping Account
                </label>
                <input
                  type="text"
                  value={formData.shipping_account}
                  onChange={(e) => handleChange('shipping_account', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                  placeholder="FedEx, UPS, etc. account number"
                />
              </div>
              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                  Notes
                </label>
                <textarea
                  value={formData.notes}
                  onChange={(e) => handleChange('notes', e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                  rows={3}
                />
              </div>
            </div>
          </div>

          {/* Status Toggles */}
          <div className="mb-4">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">Status</h3>
            <div className="space-y-2">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.is_active}
                  onChange={(e) => handleChange('is_active', e.target.checked)}
                  className="rounded"
                />
                <span className="text-sm text-gray-700 dark:text-gray-300">Active Supplier</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={formData.is_preferred}
                  onChange={(e) => handleChange('is_preferred', e.target.checked)}
                  className="rounded"
                />
                <span className="text-sm text-gray-700 dark:text-gray-300">Preferred Supplier</span>
              </label>
            </div>
          </div>
        </form>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-200 dark:border-gray-700 flex items-center justify-end gap-3">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-md"
            disabled={loading}
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={loading || nameError}
            className="px-4 py-2 text-sm font-medium text-white bg-violet-600 hover:bg-violet-700 rounded-md disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (isCreateMode ? 'Creating...' : 'Saving...') : (isCreateMode ? 'Create Supplier' : 'Save Changes')}
          </button>
        </div>
      </div>
    </div>
  );
};

export default SupplierEditModal;
